// ============================================================
// vocabulary-4k.js · 4000+必刷词（学术核心词族）
// Reborn新生留学
//
// 结构与 vocabulary.js 完全一致，单元 id 用 '4k-1-1' 形式，
// 因此可以直接复用 quiz.html 的默写检查与自动统计。
//
// ⚠ 如需替换为你自己的 4400 词表：
//   保持下面 { id, name, words:[{word,pos,meaning}] } 的结构即可，
//   单元 id 换成任意唯一字符串，学习页和检查页会自动适配。
// ============================================================

const VOCABULARY_4K = {

  // ---------- 1. 教育与学习 ----------
  '4k-1-1': {
    id: '4k-1-1',
    name: '教育与学习',
    words: [
      { word: 'academic', pos: 'adj.', meaning: '学术的；学院的' },
      { word: 'accommodate', pos: 'v.', meaning: '容纳；适应；提供住宿' },
      { word: 'acquire', pos: 'v.', meaning: '获得；学到；取得' },
      { word: 'adequately', pos: 'adv.', meaning: '充分地；适当地' },
      { word: 'advocate', pos: 'v./n.', meaning: '提倡；拥护者' },
      { word: 'affiliate', pos: 'v.', meaning: '附属；隶属；加入' },
      { word: 'allocate', pos: 'v.', meaning: '分配；拨给' },
      { word: 'alumni', pos: 'n.', meaning: '校友（总称）' },
      { word: 'apprentice', pos: 'n.', meaning: '学徒；见习生' },
      { word: 'assessment', pos: 'n.', meaning: '评估；评定' },
      { word: 'assign', pos: 'v.', meaning: '分配；指派；布置（作业）' },
      { word: 'attribute', pos: 'v.', meaning: '把…归因于；把…归于' },
      { word: 'bachelor', pos: 'n.', meaning: '学士；学士学位' },
      { word: 'curriculum', pos: 'n.', meaning: '课程；教学大纲' },
      { word: 'discipline', pos: 'n.', meaning: '学科；纪律；训练' },
      { word: 'dissertation', pos: 'n.', meaning: '学位论文；专题论文' },
      { word: 'distinct', pos: 'adj.', meaning: '明显的；独特的；不同的' },
      { word: 'doctoral', pos: 'adj.', meaning: '博士的' },
      { word: 'enrol', pos: 'v.', meaning: '注册；入学；报名' },
      { word: 'evaluate', pos: 'v.', meaning: '评价；估计；评估' },
      { word: 'expertise', pos: 'n.', meaning: '专业知识；专长' },
      { word: 'facilitate', pos: 'v.', meaning: '促进；使便利' },
      { word: 'faculty', pos: 'n.', meaning: '全体教师；院系' },
      { word: 'feedback', pos: 'n.', meaning: '反馈；回应' },
      { word: 'funding', pos: 'n.', meaning: '资金；资助' },
      { word: 'graduate', pos: 'v./n.', meaning: '毕业；毕业生' },
      { word: 'intellectual', pos: 'adj./n.', meaning: '智力的；知识分子' },
      { word: 'literacy', pos: 'n.', meaning: '读写能力；素养' },
      { word: 'major', pos: 'n./adj.', meaning: '专业；主要的' },
      { word: 'mentor', pos: 'n./v.', meaning: '导师；指导' },
      { word: 'peer', pos: 'n.', meaning: '同龄人；同辈' },
      { word: 'postgraduate', pos: 'adj./n.', meaning: '研究生的；研究生' },
      { word: 'practical', pos: 'adj.', meaning: '实用的；实践的' },
      { word: 'proficiency', pos: 'n.', meaning: '熟练程度；精通' },
      { word: 'qualification', pos: 'n.', meaning: '资格；学历' },
      { word: 'seminar', pos: 'n.', meaning: '研讨会；研讨课' },
      { word: 'supervisor', pos: 'n.', meaning: '导师；主管' },
      { word: 'syllabus', pos: 'n.', meaning: '教学大纲；课程安排' },
      { word: 'tuition', pos: 'n.', meaning: '学费；教学' },
      { word: 'tutor', pos: 'n./v.', meaning: '导师；辅导' },
      { word: 'undergraduate', pos: 'n./adj.', meaning: '本科生；本科的' },
      { word: 'vocational', pos: 'adj.', meaning: '职业的；职业教育的' },
      { word: 'achievement', pos: 'n.', meaning: '成就；成绩' },
      { word: 'compulsory', pos: 'adj.', meaning: '必修的；强制的' },
      { word: 'intellectualise', pos: 'v.', meaning: '使理性化；使理智化' },
      { word: 'tutorial', pos: 'n.', meaning: '辅导课； tutorial' },
      { word: 'aspiration', pos: 'n.', meaning: '抱负；志向' },
      { word: 'endeavour', pos: 'n./v.', meaning: '努力；尽力' },
      { word: 'perseverance', pos: 'n.', meaning: '毅力；坚持' },
      { word: 'proficient', pos: 'adj.', meaning: '熟练的；精通的' },
      { word: 'curriculum vitae', pos: 'n.', meaning: '简历；履历表' },
      { word: 'undertake', pos: 'v.', meaning: '承担；着手做' },
      { word: 'sophisticated', pos: 'adj.', meaning: '复杂精密的；老练的' },
      { word: 'trivial', pos: 'adj.', meaning: '琐碎的；不重要的' }
    ]
  },

  // ---------- 2. 科技与工程 ----------
  '4k-1-2': {
    id: '4k-1-2',
    name: '科技与工程',
    words: [
      { word: 'accessible', pos: 'adj.', meaning: '可获取的；易接近的' },
      { word: 'aggregate', pos: 'n./v.', meaning: '总计；聚集；合计' },
      { word: 'automate', pos: 'v.', meaning: '使自动化' },
      { word: 'compatible', pos: 'adj.', meaning: '兼容的；相容的' },
      { word: 'component', pos: 'n.', meaning: '部件；元件；组成部分' },
      { word: 'comprise', pos: 'v.', meaning: '包含；由…组成' },
      { word: 'consensus', pos: 'n.', meaning: '共识；一致意见' },
      { word: 'constant', pos: 'adj.', meaning: '不断的；恒定的' },
      { word: 'constraints', pos: 'n.', meaning: '限制；约束' },
      { word: 'contemporary', pos: 'adj.', meaning: '当代的；同时代的' },
      { word: 'controversial', pos: 'adj.', meaning: '有争议的' },
      { word: 'criterion', pos: 'n.', meaning: '标准；准则' },
      { word: 'cumulative', pos: 'adj.', meaning: '累积的' },
      { word: 'deduction', pos: 'n.', meaning: '扣除；推导；结论' },
      { word: 'demonstrate', pos: 'v.', meaning: '证明；演示；展示' },
      { word: 'detrimental', pos: 'adj.', meaning: '有害的；不利的' },
      { word: 'differentiate', pos: 'v.', meaning: '区分；使不同' },
      { word: 'discrete', pos: 'adj.', meaning: '离散的；分离的' },
      { word: 'disrupt', pos: 'v.', meaning: '扰乱；中断' },
      { word: 'emerging', pos: 'adj.', meaning: '新兴的；出现的' },
      { word: 'exploit', pos: 'v.', meaning: '利用；开发；剥削' },
      { word: 'feasible', pos: 'adj.', meaning: '可行的；行得通的' },
      { word: 'implement', pos: 'v.', meaning: '实施；执行' },
      { word: 'infrastructure', pos: 'n.', meaning: '基础设施' },
      { word: 'innovation', pos: 'n.', meaning: '创新；革新' },
      { word: 'integrate', pos: 'v.', meaning: '整合；使一体化' },
      { word: 'interface', pos: 'n./v.', meaning: '界面；接口；相互连接' },
      { word: 'intrinsic', pos: 'adj.', meaning: '内在的；固有的' },
      { word: 'legitimate', pos: 'adj.', meaning: '合法的；合理的' },
      { word: 'magnitude', pos: 'n.', meaning: '巨大；重要性；量级' },
      { word: 'mechanism', pos: 'n.', meaning: '机制；机械装置' },
      { word: 'minimal', pos: 'adj.', meaning: '最小的；极少的' },
      { word: 'monitor', pos: 'v./n.', meaning: '监测；显示器' },
      { word: 'notion', pos: 'n.', meaning: '概念；观念' },
      { word: 'optimal', pos: 'adj.', meaning: '最佳的；最适宜的' },
      { word: 'paradigm', pos: 'n.', meaning: '范式；典范' },
      { word: 'parameter', pos: 'n.', meaning: '参数；限制因素' },
      { word: 'phenomenon', pos: 'n.', meaning: '现象' },
      { word: 'precise', pos: 'adj.', meaning: '精确的；准确的' },
      { word: 'predict', pos: 'v.', meaning: '预测；预言' },
      { word: 'preliminary', pos: 'adj.', meaning: '初步的；预备的' },
      { word: 'principle', pos: 'n.', meaning: '原则；原理' },
      { word: 'procedure', pos: 'n.', meaning: '程序；步骤；手续' },
      { word: 'proportion', pos: 'n.', meaning: '比例；部分' },
      { word: 'reinforce', pos: 'v.', meaning: '加强；强化' },
      { word: 'resolve', pos: 'v.', meaning: '解决；分解' },
      { word: 'restrain', pos: 'v.', meaning: '抑制；约束' },
      { word: 'subsequent', pos: 'adj.', meaning: '随后的；后来的' },
      { word: 'subsidiary', pos: 'adj.', meaning: '次要的；附属的' },
      { word: 'transform', pos: 'v.', meaning: '转变；改造' },
      { word: 'transmit', pos: 'v.', meaning: '传输；传送；传播' },
      { word: 'underlying', pos: 'adj.', meaning: '潜在的；根本的' },
      { word: 'valid', pos: 'adj.', meaning: '有效的；合理的' },
      { word: 'versatile', pos: 'adj.', meaning: '多才多艺的；多用途的' },
      { word: 'virtual', pos: 'adj.', meaning: '虚拟的；实际上的' },
      { word: 'visual', pos: 'adj.', meaning: '视觉的' },
      { word: 'algorithm', pos: 'n.', meaning: '算法' },
      { word: 'artificial', pos: 'adj.', meaning: '人工的；人造的' },
      { word: 'automation', pos: 'n.', meaning: '自动化' },
      { word: 'simulate', pos: 'v.', meaning: '模拟；假装' },
      { word: 'sustainable', pos: 'adj.', meaning: '可持续的' },
      { word: 'synthesise', pos: 'v.', meaning: '综合；合成' },
      { word: 'threshold', pos: 'n.', meaning: '门槛；临界值' },
      { word: 'deficiency', pos: 'n.', meaning: '缺乏；不足' },
      { word: 'exponential', pos: 'adj.', meaning: '指数的；极快的' }
    ]
  },

  // ---------- 3. 环境与可持续 ----------
  '4k-1-3': {
    id: '4k-1-3',
    name: '环境与可持续',
    words: [
      { word: 'alternative', pos: 'n./adj.', meaning: '替代品；可供选择的' },
      { word: 'apparent', pos: 'adj.', meaning: '明显的；表面上的' },
      { word: 'attenuate', pos: 'v.', meaning: '减弱；衰减' },
      { word: 'coherent', pos: 'adj.', meaning: '连贯的；一致的' },
      { word: 'collapse', pos: 'v./n.', meaning: '倒塌；崩溃' },
      { word: 'commodity', pos: 'n.', meaning: '商品；日用品' },
      { word: 'compensation', pos: 'n.', meaning: '补偿；赔偿' },
      { word: 'comprehensive', pos: 'adj.', meaning: '全面的；综合的' },
      { word: 'conventional', pos: 'adj.', meaning: '传统的；常规的' },
      { word: 'depletion', pos: 'n.', meaning: '耗尽；枯竭' },
      { word: 'deteriorate', pos: 'v.', meaning: '恶化；变坏' },
      { word: 'diminish', pos: 'v.', meaning: '减少；缩小' },
      { word: 'diversity', pos: 'n.', meaning: '多样性；差异' },
      { word: 'duration', pos: 'n.', meaning: '持续时间' },
      { word: 'ecological', pos: 'adj.', meaning: '生态的' },
      { word: 'emission', pos: 'n.', meaning: '排放；散发' },
      { word: 'fluctuate', pos: 'v.', meaning: '波动；起伏' },
      { word: 'fragile', pos: 'adj.', meaning: '脆弱的；易碎的' },
      { word: 'incentive', pos: 'n.', meaning: '激励；刺激' },
      { word: 'indispensable', pos: 'adj.', meaning: '不可或缺的' },
      { word: 'inevitable', pos: 'adj.', meaning: '不可避免的' },
      { word: 'inhibition', pos: 'n.', meaning: '抑制；阻碍' },
      { word: 'irreversible', pos: 'adj.', meaning: '不可逆的' },
      { word: 'mitigate', pos: 'v.', meaning: '减轻；缓解' },
      { word: 'offset', pos: 'v./n.', meaning: '抵消；补偿' },
      { word: 'pollutant', pos: 'n.', meaning: '污染物' },
      { word: 'preservation', pos: 'n.', meaning: '保护；保存' },
      { word: 'prioritise', pos: 'v.', meaning: '优先考虑；优先处理' },
      { word: 'recycle', pos: 'v.', meaning: '回收利用；再循环' },
      { word: 'regenerate', pos: 'v.', meaning: '再生；恢复' },
      { word: 'renewable', pos: 'adj.', meaning: '可再生的' },
      { word: 'residue', pos: 'n.', meaning: '残留物；残渣' },
      { word: 'restore', pos: 'v.', meaning: '恢复；修复' },
      { word: 'retain', pos: 'v.', meaning: '保留；保持' },
      { word: 'scarce', pos: 'adj.', meaning: '稀缺的；不足的' },
      { word: 'stability', pos: 'n.', meaning: '稳定；稳定性' },
      { word: 'stimulus', pos: 'n.', meaning: '刺激；刺激物' },
      { word: 'substitute', pos: 'n./v.', meaning: '替代品；代替' },
      { word: 'terrain', pos: 'n.', meaning: '地形；地带' },
      { word: 'transparency', pos: 'n.', meaning: '透明度；公开性' },
      { word: 'accumulate', pos: 'v.', meaning: '积累；积聚' },
      { word: 'conserve', pos: 'v.', meaning: '保护；节约' },
      { word: 'contaminate', pos: 'v.', meaning: '污染；弄脏' },
      { word: 'hazardous', pos: 'adj.', meaning: '危险的；有害的' },
      { word: 'renewable resource', pos: 'n.', meaning: '可再生资源' },
      { word: 'species', pos: 'n.', meaning: '物种；种类' },
      { word: 'urbanisation', pos: 'n.', meaning: '城市化' },
      { word: 'conservation', pos: 'n.', meaning: '保护；保育' },
      { word: 'ecosystem', pos: 'n.', meaning: '生态系统' },
      { word: 'greenhouse', pos: 'n.', meaning: '温室；暖房' },
      { word: 'fossil', pos: 'n./adj.', meaning: '化石；化石的' },
      { word: 'solar', pos: 'adj.', meaning: '太阳的；太阳能的' },
      { word: 'hydro', pos: 'n.', meaning: '水力；水电' },
      { word: 'turbine', pos: 'n.', meaning: '涡轮；涡轮机' }
    ]
  },

  // ---------- 4. 健康与医学 ----------
  '4k-1-4': {
    id: '4k-1-4',
    name: '健康与医学',
    words: [
      { word: 'acute', pos: 'adj.', meaning: '急性的；严重的；敏锐的' },
      { word: 'adequate', pos: 'adj.', meaning: '充足的；适当的' },
      { word: 'adverse', pos: 'adj.', meaning: '不利的；有害的' },
      { word: 'aesthetic', pos: 'adj.', meaning: '美学的；审美的' },
      { word: 'antibiotic', pos: 'n.', meaning: '抗生素' },
      { word: 'chronic', pos: 'adj.', meaning: '慢性的；长期的' },
      { word: 'clinical', pos: 'adj.', meaning: '临床的' },
      { word: 'comparable', pos: 'adj.', meaning: '可比较的；类似的' },
      { word: 'cure', pos: 'v./n.', meaning: '治愈；疗法' },
      { word: 'diagnose', pos: 'v.', meaning: '诊断' },
      { word: 'disability', pos: 'n.', meaning: '残疾；障碍' },
      { word: 'disorder', pos: 'n.', meaning: '失调；紊乱；疾病' },
      { word: 'dose', pos: 'n.', meaning: '剂量；一剂' },
      { word: 'equilibrium', pos: 'n.', meaning: '平衡；均衡' },
      { word: 'episode', pos: 'n.', meaning: '一集；一段经历' },
      { word: 'eradicate', pos: 'v.', meaning: '根除；消灭' },
      { word: 'fatigue', pos: 'n.', meaning: '疲劳；劳累' },
      { word: 'hygiene', pos: 'n.', meaning: '卫生；卫生学' },
      { word: 'immune', pos: 'adj.', meaning: '免疫的' },
      { word: 'immunisation', pos: 'n.', meaning: '免疫接种' },
      { word: 'inadequate', pos: 'adj.', meaning: '不足的；不适当的' },
      { word: 'infectious', pos: 'adj.', meaning: '传染性的' },
      { word: 'inflammation', pos: 'n.', meaning: '炎症' },
      { word: 'inhibit', pos: 'v.', meaning: '抑制；阻碍' },
      { word: 'injury', pos: 'n.', meaning: '伤害；损伤' },
      { word: 'intense', pos: 'adj.', meaning: '强烈的；激烈的' },
      { word: 'intervene', pos: 'v.', meaning: '干预；介入' },
      { word: 'metabolism', pos: 'n.', meaning: '新陈代谢' },
      { word: 'mild', pos: 'adj.', meaning: '轻微的；温和的' },
      { word: 'moderate', pos: 'adj.', meaning: '适度的；温和的' },
      { word: 'mortality', pos: 'n.', meaning: '死亡率；死亡' },
      { word: 'nutrient', pos: 'n.', meaning: '营养物' },
      { word: 'obesity', pos: 'n.', meaning: '肥胖症' },
      { word: 'onset', pos: 'n.', meaning: '发作；开始' },
      { word: 'optimum', pos: 'n./adj.', meaning: '最佳；最优的' },
      { word: 'oral', pos: 'adj.', meaning: '口部的；口服的' },
      { word: 'outcome', pos: 'n.', meaning: '结果；结局' },
      { word: 'parallel', pos: 'adj.', meaning: '平行的；相同的' },
      { word: 'pathogen', pos: 'n.', meaning: '病原体' },
      { word: 'physician', pos: 'n.', meaning: '内科医生；医师' },
      { word: 'prescription', pos: 'n.', meaning: '处方；药方' },
      { word: 'prevention', pos: 'n.', meaning: '预防；防止' },
      { word: 'prognosis', pos: 'n.', meaning: '预后；预断' },
      { word: 'psychology', pos: 'n.', meaning: '心理学；心理' },
      { word: 'rehabilitation', pos: 'n.', meaning: '康复；恢复' },
      { word: 'sanitation', pos: 'n.', meaning: '卫生设施；公共卫生' },
      { word: 'sedentary', pos: 'adj.', meaning: '久坐的；定居的' },
      { word: 'sequence', pos: 'n.', meaning: '顺序；序列' },
      { word: 'severe', pos: 'adj.', meaning: '严重的；剧烈的' },
      { word: 'surgery', pos: 'n.', meaning: '外科手术' },
      { word: 'symptom', pos: 'n.', meaning: '症状；征兆' },
      { word: 'therapy', pos: 'n.', meaning: '治疗；疗法' },
      { word: 'vaccine', pos: 'n.', meaning: '疫苗' },
      { word: 'vascular', pos: 'adj.', meaning: '血管的' },
      { word: 'vital', pos: 'adj.', meaning: '至关重要的；生命的' },
      { word: 'anxiety', pos: 'n.', meaning: '焦虑；忧虑' },
      { word: 'depression', pos: 'n.', meaning: '抑郁；沮丧' },
      { word: 'insomnia', pos: 'n.', meaning: '失眠' },
      { word: 'nutrition', pos: 'n.', meaning: '营养；营养学' },
      { word: 'obese', pos: 'adj.', meaning: '肥胖的' },
      { word: 'physiological', pos: 'adj.', meaning: '生理的' },
      { word: 'psychological', pos: 'adj.', meaning: '心理的' },
      { word: 'wellbeing', pos: 'n.', meaning: '健康；幸福感' }
    ]
  },

  // ---------- 5. 商业与经济 ----------
  '4k-1-5': {
    id: '4k-1-5',
    name: '商业与经济',
    words: [
      { word: 'accountability', pos: 'n.', meaning: '问责制；责任' },
      { word: 'acquisition', pos: 'n.', meaning: '收购；获得' },
      { word: 'aggressive', pos: 'adj.', meaning: '好斗的；有闯劲的' },
      { word: 'allocation', pos: 'n.', meaning: '分配；配置' },
      { word: 'anticipate', pos: 'v.', meaning: '预期；预料' },
      { word: 'appraisal', pos: 'n.', meaning: '评价；评估' },
      { word: 'asset', pos: 'n.', meaning: '资产；财产' },
      { word: 'audit', pos: 'n./v.', meaning: '审计；审核' },
      { word: 'authorize', pos: 'v.', meaning: '授权；批准' },
      { word: 'bureaucracy', pos: 'n.', meaning: '官僚机构；官僚作风' },
      { word: 'capital', pos: 'n.', meaning: '资本；资金' },
      { word: 'commerce', pos: 'n.', meaning: '商业；贸易' },
      { word: 'competence', pos: 'n.', meaning: '能力；胜任' },
      { word: 'corporate', pos: 'adj.', meaning: '公司的；法人的' },
      { word: 'correlation', pos: 'n.', meaning: '相关性；相互关系' },
      { word: 'credibility', pos: 'n.', meaning: '可信度；信誉' },
      { word: 'currency', pos: 'n.', meaning: '货币；流通' },
      { word: 'deficit', pos: 'n.', meaning: '赤字；不足' },
      { word: 'distort', pos: 'v.', meaning: '扭曲；歪曲' },
      { word: 'diverse', pos: 'adj.', meaning: '多样的；不同的' },
      { word: 'domestic', pos: 'adj.', meaning: '国内的；家庭的' },
      { word: 'elaborate', pos: 'adj./v.', meaning: '精心制作的；详细说明' },
      { word: 'equity', pos: 'n.', meaning: '公平；股本；权益' },
      { word: 'expenditure', pos: 'n.', meaning: '支出；开支' },
      { word: 'income', pos: 'n.', meaning: '收入' },
      { word: 'indigenous', pos: 'adj.', meaning: '本土的；土著的' },
      { word: 'insurance', pos: 'n.', meaning: '保险；保险费' },
      { word: 'invest', pos: 'v.', meaning: '投资；投入' },
      { word: 'leverage', pos: 'v./n.', meaning: '利用；杠杆' },
      { word: 'merger', pos: 'n.', meaning: '合并；兼并' },
      { word: 'monopoly', pos: 'n.', meaning: '垄断；独占' },
      { word: 'multinational', pos: 'adj./n.', meaning: '跨国的；跨国公司' },
      { word: 'negotiate', pos: 'v.', meaning: '谈判；协商' },
      { word: 'outlay', pos: 'n.', meaning: '开支；费用' },
      { word: 'portfolio', pos: 'n.', meaning: '投资组合；作品集' },
      { word: 'profit', pos: 'n.', meaning: '利润；盈利' },
      { word: 'prosperity', pos: 'n.', meaning: '繁荣；兴旺' },
      { word: 'recession', pos: 'n.', meaning: '经济衰退' },
      { word: 'revenue', pos: 'n.', meaning: '收入；税收' },
      { word: 'subsidy', pos: 'n.', meaning: '补贴；津贴' },
      { word: 'surplus', pos: 'n./adj.', meaning: '盈余；过剩的' },
      { word: 'tariff', pos: 'n.', meaning: '关税；价目表' },
      { word: 'transaction', pos: 'n.', meaning: '交易；业务' },
      { word: 'turnover', pos: 'n.', meaning: '营业额；周转率' },
      { word: 'volatile', pos: 'adj.', meaning: '易变的；波动大的' },
      { word: 'consumer', pos: 'n.', meaning: '消费者' },
      { word: 'retail', pos: 'n./v.', meaning: '零售' },
      { word: 'wholesale', pos: 'n./adj.', meaning: '批发' },
      { word: 'entrepreneur', pos: 'n.', meaning: '企业家' },
      { word: 'liability', pos: 'n.', meaning: '责任；债务' },
      { word: 'amortise', pos: 'v.', meaning: '摊销；分摊' },
      { word: 'collateral', pos: 'n.', meaning: '抵押品；担保物' },
      { word: 'diversify', pos: 'v.', meaning: '使多样化' },
      { word: 'marketplace', pos: 'n.', meaning: '市场；集市' }
    ]
  },

  // ---------- 6. 政府与法律 ----------
  '4k-1-6': {
    id: '4k-1-6',
    name: '政府与法律',
    words: [
      { word: 'abolish', pos: 'v.', meaning: '废除；取消' },
      { word: 'adhere', pos: 'v.', meaning: '遵守；坚持' },
      { word: 'administration', pos: 'n.', meaning: '管理；行政部门' },
      { word: 'amend', pos: 'v.', meaning: '修订；修改' },
      { word: 'amendment', pos: 'n.', meaning: '修正案；修改' },
      { word: 'authority', pos: 'n.', meaning: '权威；当局' },
      { word: 'autonomy', pos: 'n.', meaning: '自治；自主权' },
      { word: 'bias', pos: 'n.', meaning: '偏见；偏差' },
      { word: 'bill', pos: 'n.', meaning: '法案；账单' },
      { word: 'censure', pos: 'v./n.', meaning: '严厉批评；谴责' },
      { word: 'civic', pos: 'adj.', meaning: '公民的；市政的' },
      { word: 'coalition', pos: 'n.', meaning: '联盟；联合政府' },
      { word: 'compliance', pos: 'n.', meaning: '遵守；合规' },
      { word: 'constituent', pos: 'n.', meaning: '选民；成分' },
      { word: 'constitute', pos: 'v.', meaning: '构成；组成' },
      { word: 'constitution', pos: 'n.', meaning: '宪法；构成' },
      { word: 'constrain', pos: 'v.', meaning: '限制；约束' },
      { word: 'consult', pos: 'v.', meaning: '咨询；请教' },
      { word: 'debate', pos: 'n./v.', meaning: '辩论；争论' },
      { word: 'delegation', pos: 'n.', meaning: '代表团；授权' },
      { word: 'democracy', pos: 'n.', meaning: '民主；民主国家' },
      { word: 'dissent', pos: 'n.', meaning: '异议；不同意' },
      { word: 'district', pos: 'n.', meaning: '区；地区' },
      { word: 'elected', pos: 'adj.', meaning: '选举产生的' },
      { word: 'enforce', pos: 'v.', meaning: '执行；强制实施' },
      { word: 'federal', pos: 'adj.', meaning: '联邦的' },
      { word: 'legislation', pos: 'n.', meaning: '立法；法规' },
      { word: 'mandate', pos: 'n./v.', meaning: '授权；指令' },
      { word: 'minority', pos: 'n.', meaning: '少数；少数民族' },
      { word: 'nominate', pos: 'v.', meaning: '提名；任命' },
      { word: 'ordinance', pos: 'n.', meaning: '条例；法令' },
      { word: 'parliament', pos: 'n.', meaning: '议会；国会' },
      { word: 'policy', pos: 'n.', meaning: '政策；方针' },
      { word: 'potential', pos: 'n./adj.', meaning: '潜力；潜在的' },
      { word: 'proceed', pos: 'v.', meaning: '继续进行；起诉' },
      { word: 'protest', pos: 'n./v.', meaning: '抗议；反对' },
      { word: 'referendum', pos: 'n.', meaning: '公民投票；公投' },
      { word: 'regulate', pos: 'v.', meaning: '监管；调节' },
      { word: 'representation', pos: 'n.', meaning: '代表；代理' },
      { word: 'resistance', pos: 'n.', meaning: '抵抗；阻力' },
      { word: 'restrict', pos: 'v.', meaning: '限制；约束' },
      { word: 'scheme', pos: 'n.', meaning: '计划；方案' },
      { word: 'sector', pos: 'n.', meaning: '部门；领域' },
      { word: 'sceptical', pos: 'adj.', meaning: '怀疑的' },
      { word: 'sovereign', pos: 'adj.', meaning: '主权的；独立的' },
      { word: 'stipulate', pos: 'v.', meaning: '规定；约定' },
      { word: 'subordinate', pos: 'adj./n.', meaning: '下级的；从属的' },
      { word: 'surveillance', pos: 'n.', meaning: '监控；监视' },
      { word: 'taxation', pos: 'n.', meaning: '税收；征税' },
      { word: 'jurisdiction', pos: 'n.', meaning: '管辖权；司法权' },
      { word: 'penalty', pos: 'n.', meaning: '处罚；罚款' },
      { word: 'petition', pos: 'n./v.', meaning: '请愿；申请' },
      { word: 'amnesty', pos: 'n.', meaning: '大赦；特赦' }
    ]
  },

  // ---------- 7. 社会与文化 ----------
  '4k-1-7': {
    id: '4k-1-7',
    name: '社会与文化',
    words: [
      { word: 'abstract', pos: 'adj.', meaning: '抽象的；摘要的' },
      { word: 'adolescent', pos: 'adj./n.', meaning: '青春期的；青少年' },
      { word: 'affinity', pos: 'n.', meaning: '亲和力；喜爱' },
      { word: 'alien', pos: 'adj./n.', meaning: '陌生的；外来的；外星人' },
      { word: 'allegiance', pos: 'n.', meaning: '忠诚；效忠' },
      { word: 'ancestor', pos: 'n.', meaning: '祖先；先辈' },
      { word: 'anthropology', pos: 'n.', meaning: '人类学' },
      { word: 'arbitrary', pos: 'adj.', meaning: '任意的；武断的' },
      { word: 'assimilate', pos: 'v.', meaning: '同化；吸收' },
      { word: 'asylum', pos: 'n.', meaning: '庇护；避难所' },
      { word: 'coincide', pos: 'v.', meaning: '同时发生；一致' },
      { word: 'colonial', pos: 'adj.', meaning: '殖民地的' },
      { word: 'commemorate', pos: 'v.', meaning: '纪念；纪念' },
      { word: 'complexity', pos: 'n.', meaning: '复杂性；复杂' },
      { word: 'conceive', pos: 'v.', meaning: '构想；认为' },
      { word: 'connotation', pos: 'n.', meaning: '内涵；言外之意' },
      { word: 'correlate', pos: 'v.', meaning: '相关；关联' },
      { word: 'cultural', pos: 'adj.', meaning: '文化的' },
      { word: 'demographic', pos: 'adj./n.', meaning: '人口统计的；人口' },
      { word: 'doctrine', pos: 'n.', meaning: '学说；教义' },
      { word: 'dominant', pos: 'adj.', meaning: '占主导地位的' },
      { word: 'elite', pos: 'n./adj.', meaning: '精英的；精英' },
      { word: 'emigrate', pos: 'v.', meaning: '移居国外' },
      { word: 'emphasis', pos: 'n.', meaning: '强调；重点' },
      { word: 'ethnic', pos: 'adj.', meaning: '种族的；民族的' },
      { word: 'exotic', pos: 'adj.', meaning: '异国情调的；奇异的' },
      { word: 'gender', pos: 'n.', meaning: '性别' },
      { word: 'generation', pos: 'n.', meaning: '一代人' },
      { word: 'heritage', pos: 'n.', meaning: '遗产；传统' },
      { word: 'hierarchy', pos: 'n.', meaning: '等级制度' },
      { word: 'hostile', pos: 'adj.', meaning: '敌对的；不友好的' },
      { word: 'ideology', pos: 'n.', meaning: '意识形态' },
      { word: 'immigrate', pos: 'v.', meaning: '移入；移民' },
      { word: 'implication', pos: 'n.', meaning: '含义；影响' },
      { word: 'inequality', pos: 'n.', meaning: '不平等' },
      { word: 'institution', pos: 'n.', meaning: '机构；制度' },
      { word: 'intervention', pos: 'n.', meaning: '干预；介入' },
      { word: 'iterate', pos: 'v.', meaning: '迭代；反复' },
      { word: 'multicultural', pos: 'adj.', meaning: '多元文化的' },
      { word: 'nurture', pos: 'v./n.', meaning: '培育；养育' },
      { word: 'paradox', pos: 'n.', meaning: '悖论；矛盾' },
      { word: 'prejudice', pos: 'n.', meaning: '偏见；成见' },
      { word: 'prestige', pos: 'n.', meaning: '声望；威望' },
      { word: 'primitive', pos: 'adj.', meaning: '原始的；简陋的' },
      { word: 'radical', pos: 'adj.', meaning: '激进的；根本的' },
      { word: 'reconcile', pos: 'v.', meaning: '调和；和解' },
      { word: 'rite', pos: 'n.', meaning: '仪式；惯例' },
      { word: 'ritual', pos: 'n.', meaning: '仪式；例行公事' },
      { word: 'segment', pos: 'n.', meaning: '部分；群体' },
      { word: 'stereotype', pos: 'n.', meaning: '刻板印象' },
      { word: 'symbolism', pos: 'n.', meaning: '象征意义' },
      { word: 'taboo', pos: 'n./adj.', meaning: '禁忌；忌讳的' },
      { word: 'tolerance', pos: 'n.', meaning: '容忍；宽容' },
      { word: 'tradition', pos: 'n.', meaning: '传统；惯例' },
      { word: 'transcend', pos: 'v.', meaning: '超越；胜过' },
      { word: 'conform', pos: 'v.', meaning: '遵守；符合' },
      { word: 'discourse', pos: 'n.', meaning: '论述；话语' },
      { word: 'gender equality', pos: 'n.', meaning: '性别平等' },
      { word: 'generation gap', pos: 'n.', meaning: '代沟' },
      { word: 'norm', pos: 'n.', meaning: '规范；常态' }
    ]
  },

  // ---------- 8. 城市与交通 ----------
  '4k-1-8': {
    id: '4k-1-8',
    name: '城市与交通',
    words: [
      { word: 'adjacent', pos: 'adj.', meaning: '邻近的；毗连的' },
      { word: 'agglomerate', pos: 'v./n.', meaning: '聚集；集合' },
      { word: 'amenity', pos: 'n.', meaning: '便利设施' },
      { word: 'commute', pos: 'v./n.', meaning: '通勤；上下班' },
      { word: 'compact', pos: 'adj.', meaning: '紧凑的；小型的' },
      { word: 'congestion', pos: 'n.', meaning: '拥堵；拥塞' },
      { word: 'conurbation', pos: 'n.', meaning: '大都市；城市群' },
      { word: 'culminate', pos: 'v.', meaning: '以…告终' },
      { word: 'degrade', pos: 'v.', meaning: '退化；降解' },
      { word: 'density', pos: 'n.', meaning: '密度；密集度' },
      { word: 'dwell', pos: 'v.', meaning: '居住； dwelling' },
      { word: 'ecology', pos: 'n.', meaning: '生态；生态学' },
      { word: 'encroach', pos: 'v.', meaning: '侵占；侵犯' },
      { word: 'fork', pos: 'n./v.', meaning: '岔路；分叉' },
      { word: 'geography', pos: 'n.', meaning: '地理；地理学' },
      { word: 'habitat', pos: 'n.', meaning: '栖息地；生境' },
      { word: 'inhabit', pos: 'v.', meaning: '居住于；栖息' },
      { word: 'itinerary', pos: 'n.', meaning: '行程；旅行路线' },
      { word: 'junction', pos: 'n.', meaning: '路口；枢纽' },
      { word: 'lease', pos: 'n./v.', meaning: '租约；出租' },
      { word: 'liable', pos: 'adj.', meaning: '有责任的；可能的' },
      { word: 'locate', pos: 'v.', meaning: '位于；坐落于' },
      { word: 'municipal', pos: 'adj.', meaning: '市政的' },
      { word: 'obscure', pos: 'adj./v.', meaning: '模糊的；使模糊' },
      { word: 'occupy', pos: 'v.', meaning: '占据；占用' },
      { word: 'pedestrian', pos: 'n./adj.', meaning: '行人；步行的' },
      { word: 'plausible', pos: 'adj.', meaning: '貌似合理的' },
      { word: 'prolong', pos: 'v.', meaning: '延长；拖延' },
      { word: 'proximity', pos: 'n.', meaning: '接近；邻近' },
      { word: 'rationale', pos: 'n.', meaning: '理由；原理' },
      { word: 'residential', pos: 'adj.', meaning: '住宅的；居住的' },
      { word: 'route', pos: 'n.', meaning: '路线；途径' },
      { word: 'rural', pos: 'adj.', meaning: '农村的；乡村的' },
      { word: 'suburb', pos: 'n.', meaning: '郊区' },
      { word: 'transit', pos: 'n.', meaning: '运输；过境' },
      { word: 'traffic', pos: 'n.', meaning: '交通；车流' },
      { word: 'transport', pos: 'n./v.', meaning: '运输；交通' },
      { word: 'urban', pos: 'adj.', meaning: '城市的' },
      { word: 'utilise', pos: 'v.', meaning: '利用；使用' },
      { word: 'vehicular', pos: 'adj.', meaning: '车辆的' },
      { word: 'viability', pos: 'n.', meaning: '可行性；生存能力' },
      { word: 'vicinity', pos: 'n.', meaning: '附近；周边' },
      { word: 'zone', pos: 'n.', meaning: '区域；地带' },
      { word: 'landfill', pos: 'n.', meaning: '垃圾填埋场' },
      { word: 'motorway', pos: 'n.', meaning: '高速公路' },
      { word: 'terminus', pos: 'n.', meaning: '终点站' },
      { word: 'depot', pos: 'n.', meaning: '车站；车库' },
      { word: 'commuter', pos: 'n.', meaning: '通勤者' },
      { word: 'waterfront', pos: 'n.', meaning: '海滨；滨水区' },
      { word: 'metropolitan', pos: 'adj.', meaning: '大都会的' },
      { word: 'municipality', pos: 'n.', meaning: '市政当局' },
      { word: 'settlement', pos: 'n.', meaning: '定居点；解决' }
    ]
  },

  // ---------- 9. 媒体与传播 ----------
  '4k-1-9': {
    id: '4k-1-9',
    name: '媒体与传播',
    words: [
      { word: 'accuracy', pos: 'n.', meaning: '准确性；精确' },
      { word: 'advertise', pos: 'v.', meaning: '做广告；宣传' },
      { word: 'anonymous', pos: 'adj.', meaning: '匿名的' },
      { word: 'articulate', pos: 'v./adj.', meaning: '清晰表达；口齿清楚的' },
      { word: 'audience', pos: 'n.', meaning: '观众；听众；读者' },
      { word: 'broadcast', pos: 'v./n.', meaning: '广播；播送' },
      { word: 'censor', pos: 'v.', meaning: '审查；删改' },
      { word: 'circulate', pos: 'v.', meaning: '传播；流通' },
      { word: 'column', pos: 'n.', meaning: '专栏；列' },
      { word: 'commentary', pos: 'n.', meaning: '评论；评注' },
      { word: 'compel', pos: 'v.', meaning: '强迫；迫使' },
      { word: 'complement', pos: 'v./n.', meaning: '补充；补足' },
      { word: 'concurrent', pos: 'adj.', meaning: '同时发生的' },
      { word: 'coverage', pos: 'n.', meaning: '报道；覆盖' },
      { word: 'deceive', pos: 'v.', meaning: '欺骗' },
      { word: 'denote', pos: 'v.', meaning: '表示；意味着' },
      { word: 'depict', pos: 'v.', meaning: '描绘；描述' },
      { word: 'disseminate', pos: 'v.', meaning: '传播；散布' },
      { word: 'endorse', pos: 'v.', meaning: '赞同；支持；代言' },
      { word: 'encompass', pos: 'v.', meaning: '包含；涵盖' },
      { word: 'entertain', pos: 'v.', meaning: '娱乐；招待' },
      { word: 'exaggerate', pos: 'v.', meaning: '夸大；夸张' },
      { word: 'exclusive', pos: 'adj.', meaning: '独有的；排他的' },
      { word: 'explicit', pos: 'adj.', meaning: '明确的；清晰的' },
      { word: 'exposure', pos: 'n.', meaning: '接触；曝光' },
      { word: 'fluency', pos: 'n.', meaning: '流利；流畅' },
      { word: 'genre', pos: 'n.', meaning: '体裁；类型' },
      { word: 'impartial', pos: 'adj.', meaning: '公正的；不偏不倚的' },
      { word: 'implicit', pos: 'adj.', meaning: '含蓄的；隐含的' },
      { word: 'impress', pos: 'v.', meaning: '使印象深刻' },
      { word: 'influence', pos: 'n./v.', meaning: '影响' },
      { word: 'interpret', pos: 'v.', meaning: '解释；口译' },
      { word: 'journalism', pos: 'n.', meaning: '新闻业；新闻学' },
      { word: 'manipulate', pos: 'v.', meaning: '操纵；控制' },
      { word: 'narrative', pos: 'n.', meaning: '叙述；故事' },
      { word: 'objective', pos: 'n./adj.', meaning: '目标；客观的' },
      { word: 'outlet', pos: 'n.', meaning: ' outlets 出口；销售点' },
      { word: 'perspective', pos: 'n.', meaning: '观点；视角' },
      { word: 'portray', pos: 'v.', meaning: '描绘；刻画' },
      { word: 'prominent', pos: 'adj.', meaning: '著名的；突出的' },
      { word: 'propaganda', pos: 'n.', meaning: '宣传' },
      { word: 'publish', pos: 'v.', meaning: '出版；发表' },
      { word: 'publicity', pos: 'n.', meaning: '宣传； publicity' },
      { word: 'reflect', pos: 'v.', meaning: '反映；反映' },
      { word: 'reliable', pos: 'adj.', meaning: '可靠的' },
      { word: 'represent', pos: 'v.', meaning: '代表；表现' },
      { word: 'source', pos: 'n.', meaning: '来源；消息源' },
      { word: 'sponsor', pos: 'v./n.', meaning: '赞助；赞助商' },
      { word: 'spin', pos: 'n./v.', meaning: '倾向性报道；旋转' },
      { word: 'status', pos: 'n.', meaning: '地位；状态' },
      { word: 'survey', pos: 'n./v.', meaning: '调查；勘察' },
      { word: 'target', pos: 'n./v.', meaning: '目标；针对' },
      { word: 'headline', pos: 'n.', meaning: '标题' },
      { word: 'tabloid', pos: 'n.', meaning: '小报' },
      { word: 'censorship', pos: 'n.', meaning: '审查制度' },
      { word: 'infotainment', pos: 'n.', meaning: '资讯娱乐' },
      { word: 'testimonial', pos: 'n.', meaning: '推荐书；证言' },
      { word: 'misleading', pos: 'adj.', meaning: '误导性的' },
      { word: 'transparent', pos: 'adj.', meaning: '透明的；公开的' }
    ]
  },

  // ---------- 10. 图表与描述（Task1 高频） ----------
  '4k-1-10': {
    id: '4k-1-10',
    name: '图表与描述',
    words: [
      { word: 'abundant', pos: 'adj.', meaning: '丰富的；大量的' },
      { word: 'annual', pos: 'adj.', meaning: '每年的' },
      { word: 'approximate', pos: 'adj./v.', meaning: '大约的；近似' },
      { word: 'basis', pos: 'n.', meaning: '基础；依据' },
      { word: 'category', pos: 'n.', meaning: '类别；范畴' },
      { word: 'commence', pos: 'v.', meaning: '开始' },
      { word: 'compensate', pos: 'v.', meaning: '补偿；弥补' },
      { word: 'concentrate', pos: 'v.', meaning: '集中' },
      { word: 'converge', pos: 'v.', meaning: '汇合；趋同' },
      { word: 'decline', pos: 'n./v.', meaning: '下降；衰退' },
      { word: 'decrease', pos: 'n./v.', meaning: '减少' },
      { word: 'displace', pos: 'v.', meaning: '取代；迫使离开' },
      { word: 'distribute', pos: 'v.', meaning: '分布；分配' },
      { word: 'emerge', pos: 'v.', meaning: '出现；兴起' },
      { word: 'equivalent', pos: 'adj./n.', meaning: '等同的；对等物' },
      { word: 'exceed', pos: 'v.', meaning: '超过；超出' },
      { word: 'forecast', pos: 'n./v.', meaning: '预测；预报' },
      { word: 'formulate', pos: 'v.', meaning: '制定；构想' },
      { word: 'fraction', pos: 'n.', meaning: '分数；小部分' },
      { word: 'generate', pos: 'v.', meaning: '产生；生成' },
      { word: 'gradient', pos: 'n.', meaning: '梯度；坡度' },
      { word: 'identical', pos: 'adj.', meaning: '完全相同的' },
      { word: 'illustrate', pos: 'v.', meaning: '说明；举例' },
      { word: 'incremental', pos: 'adj.', meaning: '渐进的；增量的' },
      { word: 'indicate', pos: 'v.', meaning: '表明；指出' },
      { word: 'inference', pos: 'n.', meaning: '推论；推断' },
      { word: 'initial', pos: 'adj.', meaning: '最初的' },
      { word: 'incline', pos: 'v.', meaning: '倾向；倾斜' },
      { word: 'intensity', pos: 'n.', meaning: '强度；烈度' },
      { word: 'interval', pos: 'n.', meaning: '间隔；区间' },
      { word: 'irregular', pos: 'adj.', meaning: '不规则的' },
      { word: 'maximum', pos: 'n./adj.', meaning: '最大值；最大的' },
      { word: 'minimum', pos: 'n./adj.', meaning: '最小值；最小的' },
      { word: 'negligible', pos: 'adj.', meaning: '微不足道的' },
      { word: 'oscillate', pos: 'v.', meaning: '振荡；波动' },
      { word: 'outnumber', pos: 'v.', meaning: '数量超过' },
      { word: 'overall', pos: 'adj./adv.', meaning: '总体的；总体上' },
      { word: 'peak', pos: 'n./v.', meaning: '高峰；达到顶点' },
      { word: 'percentage', pos: 'n.', meaning: '百分比' },
      { word: 'periodical', pos: 'adj./n.', meaning: '周期的；期刊' },
      { word: 'plateau', pos: 'n./v.', meaning: '平稳期；趋于平稳' },
      { word: 'plummet', pos: 'v.', meaning: '暴跌；骤降' },
      { word: 'portion', pos: 'n.', meaning: '部分；一份' },
      { word: 'previous', pos: 'adj.', meaning: '先前的' },
      { word: 'random', pos: 'adj.', meaning: '随机的' },
      { word: 'ratio', pos: 'n.', meaning: '比率；比例' },
      { word: 'recede', pos: 'v.', meaning: '后退；减弱' },
      { word: 'reminiscent', pos: 'adj.', meaning: '使人联想起…的' },
      { word: 'respectively', pos: 'adv.', meaning: '分别地' },
      { word: 'rise', pos: 'n./v.', meaning: '上升；增长' },
      { word: 'significant', pos: 'adj.', meaning: '显著的；重要的' },
      { word: 'slight', pos: 'adj.', meaning: '轻微的' },
      { word: 'stable', pos: 'adj.', meaning: '稳定的' },
      { word: 'statistic', pos: 'n.', meaning: '统计数据' },
      { word: 'substantial', pos: 'adj.', meaning: '大量的；实质的' },
      { word: 'surge', pos: 'n./v.', meaning: '激增；涌动' },
      { word: 'surpass', pos: 'v.', meaning: '超过；胜过' },
      { word: 'tendency', pos: 'n.', meaning: '趋势；倾向' },
      { word: 'thrive', pos: 'v.', meaning: '繁荣；茁壮成长' },
      { word: 'triple', pos: 'v./adj.', meaning: '三倍；三重的' },
      { word: 'undergo', pos: 'v.', meaning: '经历；遭受' },
      { word: 'uniform', pos: 'adj.', meaning: '统一的；均匀的' },
      { word: 'utility', pos: 'n.', meaning: '效用；公用事业' },
      { word: 'vary', pos: 'v.', meaning: '变化；不同' },
      { word: 'vast', pos: 'adj.', meaning: '广阔的；巨大的' },
      { word: 'virtually', pos: 'adv.', meaning: '几乎；实际上' },
      { word: 'volume', pos: 'n.', meaning: '体积；音量；量' },
      { word: 'witness', pos: 'v./n.', meaning: '见证；目击者' },
      { word: 'axis', pos: 'n.', meaning: '轴；轴线' },
      { word: 'scale', pos: 'n.', meaning: '规模；刻度' },
      { word: 'proportionate', pos: 'adj.', meaning: '成比例的' },
      { word: 'marginal', pos: 'adj.', meaning: '边际的；微小的' },
      { word: 'pronounced', pos: 'adj.', meaning: '明显的；显著的' },
      { word: 'sharp', pos: 'adj.', meaning: '急剧的；尖锐的' },
      { word: 'steep', pos: 'adj.', meaning: '陡峭的；急剧的' },
      { word: 'gradual', pos: 'adj.', meaning: '逐渐的' },
      { word: 'consistent', pos: 'adj.', meaning: '一致的；始终如一的' },
    ]
  }
};

if (typeof module !== 'undefined') module.exports = VOCABULARY_4K;

// ⭐ 在浏览器中挂载到 window（与 vocabulary.js 一致）
if (typeof window !== 'undefined') {
    window.VOCABULARY_4K = VOCABULARY_4K;
    console.log('✅ VOCABULARY_4K 已加载，共 ' + Object.keys(VOCABULARY_4K).length + ' 个单元');
}
